# Generated by Django 4.1.7 on 2023-04-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户账号表',
                'verbose_name_plural': '用户账号表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='token值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'token表',
                'verbose_name_plural': 'token表',
                'db_table': 'customtoken',
            },
        ),
    ]
